version: "3.9"
services:
  site:
    image: site:new
    entrypoint: /newDir/remoteClinic.sh
    ports:
      - "80:80"
      - "3307:3306"
    volumes:
      - .:/newDir
      - .\exampleApps:/var/www/html
